#pragma once
#include <Windows.h>

CONST CHAR* g_SKIN[] = { "square_blue","metal_mistral" };
CONST COLORREF g_WINDOW_BACKGROUND_COLOR[] =  { RGB(0,0,255),	RGB(150,150,150) };
CONST COLORREF g_DISPLAY_BACKGROUND_COLOR[] = { RGB(0,0,100),	RGB(50,50,50) };
CONST COLORREF g_DISPLAY_FOREGROUND_COLOR[] = { RGB(0,0,0),	RGB(0,200,0) };
